//record demerit points in speed
function carSpeed(speed){
    if(speed<=70 && speed >=70){
    if(speed <=70 && speed>=0)
    return "Ok";

    else if(speed=80)
    return "Points:2";

    else if(speed=90)
    return "Points:4";

    else if(speed=100)
    return "Points:6";

    else if(speed=110)
    return "Points:8";

    else if(speed=120)
    return "Points:10";

    else if(speed=130)
    return "Points:12";

    else if(speed=140)
    return "License suspended"

    //Points above 12=License is suspended
    //speed limit=70km/hr
    }
}